name: Build and Deploy

on:
  push:
    branches:
      - master  # Trigger on push to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Ensure babel is executable
      - name: Ensure babel is executable
        run: chmod +x node_modules/.bin/babel

      # Run the build script
      - name: Run build
        run: npm run build

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: awais957/images:img  # Replace with your Docker image name

  deploy_docker_image:
    needs: build  # This job runs after the build job
    runs-on: ubuntu-latest

    steps:
      # Checkout code (if needed for SSH setup)
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Pull Docker image from Docker Hub
      - name: Pull Docker image from Docker Hub
        run: |
          docker pull awais957/images:img  # Replace with your Docker image name

      # Deploy Docker image to your local VM via SSH
      - name: Deploy Docker image to local VM via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.MY_VM_IP}}  # Your local VM's IP address
          username: ${{ secrets.LOCAL_USER_NAME }}  # SSH username (e.g., ubuntu, root)
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key
          script: |
            # Update and install Docker if it's not already installed
            sudo apt update
            sudo apt install -y docker.io  # Make sure Docker is installed

            # Pull the Docker image from Docker Hub
            docker pull awais957/images:img  # Replace with your Docker image name

            # Run the Docker container on the local VM (exposing port 3002)
            docker run -d -p 3002:3002 awais957/images:img  # Change port if necessary

            # (Optional) Check if the container is running
            docker ps

